name: clickup_dart
description: An API wrapper for ClickUp for creating applications on top of the product.
version: 0.1.0
repository: https://github.com/ayazemre/clickup-dart

environment:
  sdk: '>=2.18.5 <3.0.0'

dev_dependencies:
  lints: ^2.0.0
  test: ^1.16.0
dependencies:
  http: ^0.13.5
