name: clickup_dart_sdk
description: A SDK for ClickUp for integrating or creating applications on top of the product.
version: 0.4.0
repository: https://github.com/ayazemre/clickup-dart-sdk

environment:
  sdk: '>=2.18.5 <4.0.0'

dev_dependencies:
  lints: ^2.0.0
  test: ^1.16.0
dependencies:
  http: ^0.13.5
  path: ^1.8.3
